"""timestamp

Revision ID: d6f2bf9ddacd
Revises: 995476a4a7a1
Create Date: 2021-06-15 15:23:28.750500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f2bf9ddacd'
down_revision = '995476a4a7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'timestamp')
    # ### end Alembic commands ###
